### ISSUE TITLE
Access to operators

### ISSUE THREAD

**Issue by chrned** [ReactiveX/RxJavaString#21]
Hi. 
We are a Java 7 shop.

We are currently integrating StringObservable into our regular Observable builder flows by using `compose` and utility methods wrapping the Observables returned by StringObservable in Observable.Transformer instances. This is quite verbose. Is this the way StringObservables are currently intended to be integrated with regular Observable builder flows?

If the operators produced by StringObservable was also available (e.g. `public static Observable.Operator<String, String> split(String regex)` on a StringObservableOperators class) we could easily integrate StringObservable in our Observable builder flows with single liners using `lift`. E.g `.lift(split(inputDelimiterRegex))`.

Is that an addition you would consider?

Regards
Christian

**Comment by akarnokd** [comment]
If you wish, you can submit a PR where the operators are factored out, but they have to go into the `internal` package which is private and shouldn't be relied upon outside the library.

**Comment by chrned** [comment]
Thank you for the quick answer. We'll have a look at that.
May I ask: What is the current recommended approach for integrating StringObservable with the regular Observable builder flow?

**Comment by akarnokd** [comment]
I don't use this library personally, but @davidmoten frequents here too. Maybe he can give you some insights.

**Comment by davidmoten** [comment]
I do use this library a lot and like not having to break method chaining. `compose(split(inputDelimiterRegex))` is what I'd use with `split` returning a `Transformer` that calls `StringObservable.split`. So you have to write `split` in this fashion but you only have to write it once then reuse (is reuse a problem for you?). Using the `Transformer` in this way is preferrable because you are not exposed to refactorings of the internal Operator classes as @akarnokd mentioned.

We could make convenient `Transformer`s available in the library. We haven't done this till now but might be worth considering. Would only be of great use for < Java 8 because lambdas are concise enough.

**Comment by chrned** [comment]
Thank you for the quick feedback guys. 
We'll use `compose` and maintain our own reusable Transformers until we are able to upgrade to Java 8.
